name: C57DBA
species: Mouse
build: GRCm38
runs:
 - 20220524_MEF
 - 20220929_P1
 - 20220929_P2
 - 20221005_MEF
 - 20221006_MEF
threads: 12
table: data/NanoStrandSeq.xls
fasta: /home/chenzonggui/species/mus_musculus/GRCm38.p6/GRCm38.canonical.genome.fa
sizes: /home/chenzonggui/species/mus_musculus/GRCm38.p6/GRCm38.canonical.genome.sizes
barcodes: ../1_NanoStrandSeq/data/nanopore_96_barcodes.fasta
benchmark_vcf: ../public/GRCm38-C57-DBA-Variant-Calls/results/C57BL_6NJ_DBA_2J_GRCm38.mgp.v5.snps_indels.dbSNP142.vcf.gz
benchmark_bed: ../public/GRCm38-C57-DBA-Variant-Calls/results/C57BL_6NJ_DBA_2J_GRCm38.mgp.v5.snps_indels.dbSNP142.bed.gz
mmi: /home/chenzonggui/species/mus_musculus/GRCm38.p6/GRCm38.canonical.mm2.map-ont.mmi
min_reads: 50000